### ISSUE TITLE
Change platform for native extension from (x86_64|aarch64)-linux to (x86_64|aarch64)-linux-gnu

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/pngcheck-ruby#32]
https://github.com/metanorma/metanorma-docker/actions/runs/7346298987/job/20010102652?pr=184#step:7:78

Probably we have to release `x86_64-linux-gnu` for this gem and `yank` `x86_64-linux` versions

**Comment by maxirmx** [comment]
It looks like there are two questions here:
(1) If we have both ```x86_64-linux``` and ```x86_64-linux-musl``` it shall work providing that compatible version of Ruby, bundler and rubygems are used (see below)
Expressir is a different story because it does not have ```x86_64-linux-musl``` because of rake-compiler-dock issues

(2) It will be correct to change ```x86_64-linux``` to ```x86_64-linux-gnu```  for all Gems with native extensions just for consistency

(3) Ruby 3.1, 3.2  provide proper support for  all combinations ```x86_64-linux``` /  ```x86_64-linux-gnu``` / ```x86_64-linux-musl``` with default versions of bundler and rubygems
Ruby 3.0, 2.7 require manual setup that shall be consistent

- If bundler 2.4.x is installed it requires rubygems 3.4.x
- If bundler 2.3.x is installed it requires rubygems 3.3.x
- Minimal bundler version is 2.3.22

So I believe we shall  _use Ruby 3.1 with default version of bundler_

**Comment by maxirmx** [comment]
I believe https://github.com/metanorma/metanorma-docker/actions/runs/7346298987/job/20010102652?pr=184#step:7:78 was using combination of Ruby version/bundler version/rubygems version that has only partial support for ```x86_64-linux``` /  ```x86_64-linux-gnu``` / ```x86_64-linux-musl```

I have changed bundler version to 2.4.22 and tests passed. I will try with the default bundler version.

**Comment by maxirmx** [comment]
Ruby with default bersion of bundler did not work for Alpine 3.16
It installed bundler 2.5.3 that failed miserably (while 2.4.22 worked like charm)

I agree,  change platform for native extension from (x86_64|aarch64)-linux to (x86_64|aarch64)-linux-gnu is the right move

**Comment by ronaldtse** [comment]
@CAMOBAP can this be closed now? Thanks!
